GET http://localhost:3000/api/movies

### Get movies with ID 3, 4 and 5
GET http://localhost:3000/api/movies?page=1&size=3

### Get movies with ID 3, 4 and 5
GET http://localhost:3000/api/movies?sort=description

###
GET http://localhost:3000/api/movies/16

###
POST http://localhost:3000/api/movies
Content-Type: application/json

{
    "title": "Atlantis tower",
    "description": "Gravimetric transporters, to the homeworld. The voyage is an interstellar astronaut. Pathway of a lunar hypnosis, grab the wind!",
    "year": "2021",
    "producerId": "1",
    "genreId": "2"
}

###
PATCH http://localhost:3000/api/movies/1
Content-Type: application/json

{
    "title": "Deep space"
}

###
PATCH http://localhost:3000/api/movies/15
Content-Type: application/json

{
    "producerId" : "1"
}

###
DELETE http://localhost:3000/api/movies/1
