GET http://localhost:3000/api/producers

###
GET http://localhost:3000/api/producers/1

###
POST http://localhost:3000/api/producers
Content-Type: application/json

{
    "firstName": "Jhon",
    "lastName": "Doe"
}

###
PATCH http://localhost:3000/api/producers/1
Content-Type: application/json

{
    "firstName": "Mike"
}

###
DELETE http://localhost:3000/api/producers/1
